In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [25]:
def cross_entropy_error(y, t):
  if y.ndim == 1:
    t = t.reshape(1, t.size)
    y = y.reshape(1, y.size)
    print("1dim")
  
  # 教師データがone-hot-vectorの場合、正解ラベルのインデックスに変換
  print(t.size, y.size)
  if t.size == y.size:
    t = t.argmax(axis=1)
    print(t)
    print("one-hot")
    
  batch_size = y.shape[0]
  print(np.arange(batch_size))
  print(batch_size)
  return -np.sum(np.log(y[np.arange(batch_size), t] + 1e-7)) / batch_size

In [26]:
y = np.array([0.1, 0.2, 0.7])
t = np.array([0, 0, 1])

# 関数を呼び出して交差エントロピー誤差を計算
error = cross_entropy_error(y, t)
print(error)

1dim
3 3
[2]
one-hot
[0]
1
0.3566748010815999


In [32]:
import numpy as np

# ソフトマックス関数
def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=-1, keepdims=True))  # オーバーフロー対策
    return exp_x / np.sum(exp_x, axis=-1, keepdims=True)

# 交差エントロピー誤差
def cross_entropy_error(y, t):
    delta = 1e-7  # ゼロ除算対策
    batch_size = y.shape[0]
    return -np.sum(t * np.log(y + delta)) / batch_size


class SoftmaxWithLoss:
  def __init__(self):
    self.loss = None #損失
    self.y = None #softmaxの出力
    self.t = None #教師データ(one-hot vector)
    
  def forward(self, x, t):
    self.t = t
    self.y = softmax(x)
    self.loss = cross_entropy_error(self.y, self.t)
    
    return self.loss
  
  def backward(self, dout=1):
    batch_size = self.t.shape[0]
    dx = (self.y - self.t) / batch_size
    print(batch_size)
    print(self.y)
    print(self.t)
    print(self.y - self.t)
    print(dx)
    
    return dx
# SoftmaxWithLossクラスの例
swl = SoftmaxWithLoss()

# forwardメソッドの例
x = np.array([[1, 2, 3], [4, 5, 6]])  # 入力
t = np.array([[0, 0, 1], [1, 0, 0]])  # 教師データ(one-hot vector)
loss = swl.forward(x, t)
#print(loss)  # 損失を出力

# backwardメソッドの例
dout = 1  # 上流から伝わる勾配
dx = swl.backward(dout)
#print(dx)  # 入力に関する勾配を出力

2
[[0.09003057 0.24472847 0.66524096]
 [0.09003057 0.24472847 0.66524096]]
[[0 0 1]
 [1 0 0]]
[[ 0.09003057  0.24472847 -0.33475904]
 [-0.90996943  0.24472847  0.66524096]]
[[ 0.04501529  0.12236424 -0.16737952]
 [-0.45498471  0.12236424  0.33262048]]
